### ISSUE TITLE
HASH

### ISSUE THREAD

**Issue by ghost** [gbfactory/Tanki-Bot#18]
hey, is it possible to obtain a HASH code using tanki's API?
i saw the old ratings banner in flash and it requires a HASH code thing to load a certain user's info
i haven't been able to make it work, but i'm curious if getting the right HASH code makes it to load the info
thanks!

this is an example
http://tankionline.com/tankiref.swf?hash=fe1a74846&server=s.eu.tankionline.com&.swf
![image](https://user-images.githubusercontent.com/39846747/140638231-2b5ba52c-9a58-44a1-9a47-f323c74a6e81.png)

**Comment by gbfactory** [comment]
Hello, sorry for this really late reply. The old tank preview banner is now gone for good. It worked with flash player (now dead) and an API that is now most likly gone. No way in making the old banner working, something should be devloped from the ground up.
